/**
 * constants/subjectLevels.jsx — dữ liệu 3 trang môn học theo cấp (Tiểu học / THCS / THPT).
 * Dữ liệu được giữ NGUYÊN VĂN từ 3 file trang cũ; phần khung giao diện dùng chung
 * nằm ở src/SubjectsLevelPage.jsx.
 */

// ─── TIEU_HOC ────────────────────────────────────────────────────
const TIEU_HOC_SUBJECTS = [
  {
    id: 1,
    name: 'Toán Tiểu Học',
    icon: 'calculate',
    level: 'Lớp 1 - 5',
    rating: 4.8,
    desc: 'Rèn tư duy tính toán, giải toán có lời văn và xây dựng nền tảng logic.',
    tags: ['Tính toán', 'Toán có lời văn', 'Rèn tư duy'],
    tutors: '260+',
    price: 'Từ 100k/giờ',
    priceNum: 100,
    categories: ['Môn chính', 'Rèn nền tảng', 'Mất gốc'],
  },
  {
    id: 2,
    name: 'Tiếng Việt',
    icon: 'menu_book',
    level: 'Lớp 1 - 5',
    rating: 4.7,
    desc: 'Luyện đọc, luyện viết, chính tả, tập làm văn và khả năng diễn đạt.',
    tags: ['Đọc hiểu', 'Chính tả', 'Tập làm văn'],
    tutors: '220+',
    price: 'Từ 100k/giờ',
    priceNum: 100,
    categories: ['Môn chính', 'Rèn nền tảng'],
  },
  {
    id: 3,
    name: 'Tiếng Anh Thiếu Nhi',
    icon: 'language',
    level: 'Lớp 1 - 5',
    rating: 4.8,
    desc: 'Học từ vựng, phát âm, giao tiếp cơ bản và tạo hứng thú với tiếng Anh.',
    tags: ['Từ vựng', 'Phát âm', 'Giao tiếp'],
    tutors: '300+',
    price: 'Từ 120k/giờ',
    priceNum: 120,
    categories: ['Ngoại ngữ', 'Môn chính'],
  },
  {
    id: 4,
    name: 'Khoa Học',
    icon: 'science',
    level: 'Lớp 4 - 5',
    rating: 4.6,
    desc: 'Tìm hiểu thế giới tự nhiên, con người, môi trường và các hiện tượng xung quanh.',
    tags: ['Tự nhiên', 'Môi trường', 'Khám phá'],
    tutors: '120+',
    price: 'Từ 100k/giờ',
    priceNum: 100,
    categories: ['Môn chính', 'Rèn nền tảng'],
  },
  {
    id: 5,
    name: 'Tin Học Cơ Bản',
    icon: 'computer',
    level: 'Lớp 3 - 5',
    rating: 4.7,
    desc: 'Làm quen máy tính, gõ phím, sử dụng phần mềm cơ bản và tư duy công nghệ.',
    tags: ['Máy tính', 'Gõ phím', 'Công nghệ'],
    tutors: '90+',
    price: 'Từ 120k/giờ',
    priceNum: 120,
    categories: ['Kỹ năng', 'Môn chính'],
  },
  {
    id: 6,
    name: 'Kỹ Năng Học Tập',
    icon: 'psychology',
    level: 'Lớp 1 - 5',
    rating: 4.7,
    desc: 'Rèn thói quen học tập, quản lý thời gian, tập trung và tự học hiệu quả.',
    tags: ['Tập trung', 'Tự học', 'Thói quen'],
    tutors: '80+',
    price: 'Từ 100k/giờ',
    priceNum: 100,
    categories: ['Kỹ năng', 'Rèn nền tảng'],
  },
];

const TIEU_HOC_CHIPS = ['Tất cả', 'Môn chính', 'Ngoại ngữ', 'Kỹ năng', 'Mất gốc', 'Rèn nền tảng'];

const TIEU_HOC_PATH = [
  {
    num: 1,
    title: 'Làm quen kiến thức',
    desc: 'Giúp học sinh hiểu bài theo cách đơn giản, dễ nhớ và gần gũi.',
  },
  {
    num: 2,
    title: 'Rèn nền tảng',
    desc: 'Củng cố Toán, Tiếng Việt, Tiếng Anh và các kỹ năng học tập cơ bản.',
  },
  {
    num: 3,
    title: 'Luyện bài đều đặn',
    desc: 'Thực hành bài tập ngắn, phù hợp với độ tuổi và khả năng tập trung.',
  },
  {
    num: 4,
    title: 'Theo dõi tiến bộ',
    desc: 'Cập nhật kết quả học tập và điều chỉnh phương pháp theo từng học sinh.',
  },
];

const TIEU_HOC_TUTORS = [
  {
    id: 1,
    name: 'Phạm Thu Hà',
    subject: 'Toán Tiểu Học',
    rating: '4.8',
    reviews: 36,
    experience: '5 năm kinh nghiệm',
    price: '130.000đ/giờ',
    initials: 'PH',
    avatar: null,
  },
  {
    id: 2,
    name: 'Nguyễn Minh Châu',
    subject: 'Tiếng Việt',
    rating: '4.7',
    reviews: 28,
    experience: '4 năm kinh nghiệm',
    price: '120.000đ/giờ',
    initials: 'MC',
    avatar: null,
  },
  {
    id: 3,
    name: 'Lê Anh Khoa',
    subject: 'Tiếng Anh Thiếu Nhi',
    rating: '4.9',
    reviews: 52,
    experience: '6 năm kinh nghiệm',
    price: '150.000đ/giờ',
    initials: 'LK',
    avatar: null,
  },
];

// ─── THCS ────────────────────────────────────────────────────────
const THCS_SUBJECTS = [
  {
    id: 1,
    name: 'Toán THCS',
    icon: 'functions',
    level: 'Lớp 6 - 9',
    rating: 4.8,
    desc: 'Củng cố đại số, hình học, giải bài tập và ôn thi vào lớp 10.',
    tags: ['Đại số', 'Hình học', 'Ôn thi vào 10'],
    tutors: '420+',
    price: 'Từ 120k/giờ',
    priceNum: 120,
    categories: ['Môn chính', 'Luyện thi', 'Mất gốc'],
  },
  {
    id: 2,
    name: 'Ngữ Văn THCS',
    icon: 'menu_book',
    level: 'Lớp 6 - 9',
    rating: 4.7,
    desc: 'Rèn đọc hiểu, viết đoạn văn, nghị luận và phân tích tác phẩm.',
    tags: ['Đọc hiểu', 'Viết văn', 'Ôn thi'],
    tutors: '300+',
    price: 'Từ 110k/giờ',
    priceNum: 110,
    categories: ['Môn chính', 'Luyện thi'],
  },
  {
    id: 3,
    name: 'Tiếng Anh THCS',
    icon: 'language',
    level: 'Lớp 6 - 9',
    rating: 4.8,
    desc: 'Nâng cao ngữ pháp, từ vựng, kỹ năng đọc hiểu và giao tiếp cơ bản.',
    tags: ['Ngữ pháp', 'Từ vựng', 'Giao tiếp'],
    tutors: '380+',
    price: 'Từ 130k/giờ',
    priceNum: 130,
    categories: ['Môn chính', 'Ngoại ngữ', 'Luyện thi'],
  },
  {
    id: 4,
    name: 'Vật Lý THCS',
    icon: 'science',
    level: 'Lớp 6 - 9',
    rating: 4.7,
    desc: 'Nắm chắc công thức, hiểu hiện tượng vật lý và luyện bài tập cơ bản.',
    tags: ['Cơ bản', 'Công thức', 'Bài tập'],
    tutors: '180+',
    price: 'Từ 120k/giờ',
    priceNum: 120,
    categories: ['Môn chính', 'Luyện thi', 'Mất gốc'],
  },
  {
    id: 5,
    name: 'Hóa Học THCS',
    icon: 'experiment',
    level: 'Lớp 8 - 9',
    rating: 4.7,
    desc: 'Làm quen hóa học, phản ứng hóa học, tính toán và kiến thức nền tảng.',
    tags: ['Lớp 8', 'Lớp 9', 'Bài tập'],
    tutors: '160+',
    price: 'Từ 120k/giờ',
    priceNum: 120,
    categories: ['Môn chính', 'Luyện thi', 'Mất gốc'],
  },
  {
    id: 6,
    name: 'Sinh Học THCS',
    icon: 'biotech',
    level: 'Lớp 6 - 9',
    rating: 4.6,
    desc: 'Học kiến thức sinh học cơ bản, cơ thể người, thực vật, động vật và môi trường.',
    tags: ['Lý thuyết', 'Cơ thể người', 'Môi trường'],
    tutors: '130+',
    price: 'Từ 110k/giờ',
    priceNum: 110,
    categories: ['Môn chính', 'Luyện thi'],
  },
  {
    id: 7,
    name: 'Lịch Sử THCS',
    icon: 'history_edu',
    level: 'Lớp 6 - 9',
    rating: 4.6,
    desc: 'Học theo dòng thời gian, ghi nhớ sự kiện và hiểu bối cảnh lịch sử.',
    tags: ['Sự kiện', 'Ghi nhớ', 'Ôn thi'],
    tutors: '110+',
    price: 'Từ 100k/giờ',
    priceNum: 100,
    categories: ['Môn chính', 'Luyện thi'],
  },
  {
    id: 8,
    name: 'Địa Lý THCS',
    icon: 'public',
    level: 'Lớp 6 - 9',
    rating: 4.6,
    desc: 'Nắm kiến thức địa lý tự nhiên, dân cư, kinh tế và kỹ năng đọc bản đồ.',
    tags: ['Bản đồ', 'Tự nhiên', 'Kinh tế'],
    tutors: '100+',
    price: 'Từ 100k/giờ',
    priceNum: 100,
    categories: ['Môn chính', 'Luyện thi'],
  },
  {
    id: 9,
    name: 'Tin Học THCS',
    icon: 'computer',
    level: 'Lớp 6 - 9',
    rating: 4.7,
    desc: 'Làm quen tin học, tư duy thuật toán, lập trình cơ bản và kỹ năng máy tính.',
    tags: ['Tin học', 'Thuật toán', 'Lập trình'],
    tutors: '140+',
    price: 'Từ 130k/giờ',
    priceNum: 130,
    categories: ['Kỹ năng', 'Môn chính'],
  },
];

const THCS_CHIPS = ['Tất cả', 'Môn chính', 'Luyện thi', 'Ngoại ngữ', 'Kỹ năng', 'Mất gốc'];

const THCS_PATH = [
  {
    num: 1,
    title: 'Kiểm tra kiến thức nền',
    desc: 'Xác định môn học còn yếu và các chuyên đề cần củng cố.',
  },
  {
    num: 2,
    title: 'Củng cố theo lớp',
    desc: 'Học lại kiến thức trọng tâm lớp 6 - 9 theo từng môn.',
  },
  {
    num: 3,
    title: 'Luyện bài & sửa lỗi',
    desc: 'Thực hành bài tập, sửa lỗi sai và rèn phương pháp làm bài.',
  },
  {
    num: 4,
    title: 'Ôn thi chuyển cấp',
    desc: 'Luyện đề, quản lý thời gian và chuẩn bị cho kỳ thi vào lớp 10.',
  },
];

const THCS_TUTORS = [
  {
    id: 1,
    name: 'Hoàng Đức Minh',
    subject: 'Toán THCS',
    rating: '4.8',
    reviews: 48,
    experience: '7 năm kinh nghiệm',
    price: '150.000đ/giờ',
    initials: 'HM',
    avatar: null,
  },
  {
    id: 2,
    name: 'Trần Ngọc Mai',
    subject: 'Ngữ Văn THCS',
    rating: '4.7',
    reviews: 34,
    experience: '5 năm kinh nghiệm',
    price: '130.000đ/giờ',
    initials: 'NM',
    avatar: null,
  },
  {
    id: 3,
    name: 'Phạm Anh Tuấn',
    subject: 'Tiếng Anh THCS',
    rating: '4.9',
    reviews: 61,
    experience: '6 năm kinh nghiệm',
    price: '160.000đ/giờ',
    initials: 'AT',
    avatar: null,
  },
];

// ─── THPT ────────────────────────────────────────────────────────
const THPT_SUBJECTS = [
  {
    id: 1,
    name: 'Toán Học',
    icon: 'functions',
    level: 'Lớp 10 - 12',
    desc: 'Lấy lại căn bản, nâng cao tư duy giải toán, luyện đề chuẩn cấu trúc THPT Quốc Gia.',
    tags: ['Đại số', 'Hình học', 'Luyện thi ĐH'],
    tutors: '320+',
    price: '150k/h',
    priceNum: 150,
    categories: ['Môn chính', 'Luyện thi', 'Mất gốc'],
  },
  {
    id: 2,
    name: 'Ngữ Văn',
    icon: 'menu_book',
    level: 'Lớp 10 - 12',
    desc: 'Rèn kỹ năng viết nghị luận, phân tích tác phẩm văn học sâu sắc, tự tin đạt điểm cao.',
    tags: ['Đọc hiểu', 'Nghị luận'],
    tutors: '250+',
    price: '130k/h',
    priceNum: 130,
    categories: ['Môn chính', 'Luyện thi'],
  },
  {
    id: 3,
    name: 'Tiếng Anh',
    icon: 'language',
    level: 'Lớp 10 - 12',
    desc: 'Nắm vững ngữ pháp, từ vựng chuẩn bị cho kỳ thi THPT và các chứng chỉ quốc tế.',
    tags: ['Ngữ pháp', 'IELTS căn bản'],
    tutors: '410+',
    price: '160k/h',
    priceNum: 160,
    categories: ['Môn chính', 'Ngoại ngữ', 'Luyện thi'],
  },
  {
    id: 4,
    name: 'Vật Lý',
    icon: 'science',
    level: 'Lớp 10 - 12',
    desc: 'Hệ thống hóa kiến thức cơ bản, rèn luyện kỹ năng giải bài tập trắc nghiệm và tự luận.',
    tags: ['Cơ học', 'Điện học'],
    tutors: '180+',
    price: '140k/h',
    priceNum: 140,
    categories: ['Môn chính', 'Luyện thi'],
  },
  {
    id: 5,
    name: 'Hóa Học',
    icon: 'experiment',
    level: 'Lớp 10 - 12',
    desc: 'Nắm vững lý thuyết, phản ứng hóa học, và phương pháp giải bài tập định lượng.',
    tags: ['Hữu cơ', 'Vô cơ'],
    tutors: '160+',
    price: '140k/h',
    priceNum: 140,
    categories: ['Môn chính', 'Luyện thi', 'Mất gốc'],
  },
  {
    id: 6,
    name: 'Sinh Học',
    icon: 'biotech',
    level: 'Lớp 10 - 12',
    desc: 'Tìm hiểu quy luật di truyền, cấu trúc tế bào và sinh thái học chuẩn chương trình.',
    tags: ['Di truyền', 'Tế bào'],
    tutors: '140+',
    price: '130k/h',
    priceNum: 130,
    categories: ['Môn chính', 'Luyện thi'],
  },
  {
    id: 7,
    name: 'Lịch Sử',
    icon: 'history_edu',
    level: 'Lớp 10 - 12',
    desc: 'Phương pháp học thông minh giúp ghi nhớ sự kiện lịch sử nhanh chóng và lâu dài.',
    tags: ['Việt Nam', 'Thế giới'],
    tutors: '110+',
    price: '120k/h',
    priceNum: 120,
    categories: ['Môn chính', 'Luyện thi'],
  },
  {
    id: 8,
    name: 'Địa Lý',
    icon: 'public',
    level: 'Lớp 10 - 12',
    desc: 'Kỹ năng sử dụng Atlat, phân tích biểu đồ và hiểu biết về tự nhiên, kinh tế - xã hội.',
    tags: ['Tự nhiên', 'Kinh tế'],
    tutors: '120+',
    price: '120k/h',
    priceNum: 120,
    categories: ['Môn chính', 'Luyện thi'],
  },
  {
    id: 9,
    name: 'Tin Học',
    icon: 'computer',
    level: 'Lớp 10 - 12',
    desc: 'Lập trình Pascal, Python cơ bản, thuật toán và kỹ năng máy tính thực hành.',
    tags: ['Lập trình', 'Thuật toán'],
    tutors: '150+',
    price: '140k/h',
    priceNum: 140,
    categories: ['Kỹ năng', 'Môn chính'],
  },
  {
    id: 10,
    name: 'GDCD',
    icon: 'gavel',
    level: 'Lớp 10 - 12',
    desc: 'Kiến thức pháp luật, đạo đức và quyền công dân phục vụ ôn thi THPT Quốc Gia.',
    tags: ['Pháp luật', 'Đạo đức'],
    tutors: '80+',
    price: '100k/h',
    priceNum: 100,
    categories: ['Môn chính', 'Luyện thi'],
  },
  {
    id: 11,
    name: 'Tiếng Pháp',
    icon: 'translate',
    level: 'Lớp 10 - 12',
    desc: 'Học Tiếng Pháp từ giao tiếp cơ bản đến ôn thi tốt nghiệp cùng gia sư bản ngữ.',
    tags: ['Giao tiếp', 'Luyện thi'],
    tutors: '45+',
    price: '160k/h',
    priceNum: 160,
    categories: ['Ngoại ngữ', 'Luyện thi'],
  },
  {
    id: 12,
    name: 'Luyện Thi Tổng Hợp',
    icon: 'quiz',
    level: 'Lớp 12',
    desc: 'Ôn luyện toàn diện các môn thi THPT Quốc Gia với phương pháp học hiệu quả.',
    tags: ['Ôn thi', 'THPT QG'],
    tutors: '200+',
    price: '170k/h',
    priceNum: 170,
    categories: ['Luyện thi', 'Mất gốc'],
  },
];

const THPT_CHIPS = ['Tất cả', 'Môn chính', 'Luyện thi', 'Ngoại ngữ', 'Kỹ năng', 'Mất gốc'];

const THPT_PATH = [
  { num: 1, title: 'Kiểm tra nền tảng', desc: 'Đánh giá năng lực hiện tại để xác định lỗ hổng kiến thức.' },
  { num: 2, title: 'Củng cố kiến thức', desc: 'Xây dựng lại nền tảng vững chắc theo SGK chuẩn Bộ GD.' },
  { num: 3, title: 'Luyện bài theo dạng', desc: 'Phân loại và thực hành các dạng bài tập từ cơ bản đến nâng cao.' },
  { num: 4, title: 'Luyện đề & đánh giá', desc: 'Thi thử định kỳ với đề chuẩn cấu trúc thi THPT Quốc Gia.' },
];

const THPT_TUTORS = [
  {
    id: 1,
    name: 'Nguyễn Thị Hương',
    subject: 'Toán THPT',
    rating: '4.8',
    reviews: 42,
    initials: 'NH',
    avatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDB3di3MkJq42puZoUYt_hubuA4JwwpvNEvoci540jCoQ03xDObMn9G4Qpe92z5z3QKEYUKontff2oqIxSQOgMQE5S-1LWRJeQ_rM0iK1xALul0w6B6oHlpmmvQs75FMbeBB1vqA_2rADxSebJv6sIbUEHxiZUyjO0zMb8Ja75NZs3-NfIs7HW8Mm1gQNmku8nYAiF943lAtSsoFLTyr8Krp9U7lXoBAj60c2e4ZUY_lu9AqRL-qDKnziyAC40JAUKYMYyIdOOmvfc',
  },
  {
    id: 2,
    name: 'Trần Minh Anh',
    subject: 'Tiếng Anh / IELTS',
    rating: '4.9',
    reviews: 85,
    initials: 'MA',
    avatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuD7NB_cGU1Z5nSVacvisaxNK3duky8o85yH_Zie_WVVPDQGHXdWKxaHnZFuvZ7ABP_d2ldGnd7CvyaKLnTfxVbBzvBxy-zQj91aWfdHRlgey-o6BO0sEiQCVox5RHyXgtTqXg4EGN8YoOZ1pXSDPtzpAV__shGTuRglghHcCN8704gPUQmGMKKZxPDG67Cc5ElENPemTG7-ryLDpWg7uh6So9HmKYPaJqTNTl0nRnpt_OS7OZ5Vr8c80il1xkUxqrYqr5q1ij8ONdU',
  },
  {
    id: 3,
    name: 'Lê Quốc Bảo',
    subject: 'Vật Lý THPT',
    rating: '4.7',
    reviews: 31,
    initials: 'LB',
    avatar: null,
  },
];

export const TIEU_HOC_LEVEL = {
  key: 'tieuhoc',
  subjects: TIEU_HOC_SUBJECTS,
  filterChips: TIEU_HOC_CHIPS,
  learningPath: TIEU_HOC_PATH,
  featuredTutors: TIEU_HOC_TUTORS,
  hero: {
    title: "Môn Học Cấp Tiểu Học",
    subtitle: "Xây dựng nền tảng học tập vững chắc cho học sinh tiểu học với các môn học cơ bản và gia sư tận tâm.",
    stats: [
      { value: "12", label: 'môn học' },
      { value: "650+", label: 'gia sư' },
      { value: "Từ 90k", label: '/giờ' },
      { value: 'Linh hoạt', label: 'Online & trực tiếp' },
    ],
  },
  searchPlaceholder: "Tìm môn học cấp Tiểu học...",
  gridTitle: "Danh Sách Môn Học Tiểu Học",
  gridSubtitle: "Chọn môn học phù hợp để giúp học sinh xây dựng nền tảng vững chắc.",
  pathTitle: "Lộ Trình Học Tiểu Học Gợi Ý",
  tutorsTitle: "Gia Sư Nổi Bật Cho Tiểu Học",
  ctaTitle: "Chưa Biết Bé Nên Bắt Đầu Từ Môn Nào?",
  ctaText: "Trả lời vài câu hỏi ngắn, EduX sẽ gợi ý môn học và gia sư phù hợp với độ tuổi, trình độ và mục tiêu của bé.",
};

export const THCS_LEVEL = {
  key: 'thcs',
  subjects: THCS_SUBJECTS,
  filterChips: THCS_CHIPS,
  learningPath: THCS_PATH,
  featuredTutors: THCS_TUTORS,
  hero: {
    title: "Môn Học Cấp THCS",
    subtitle: "Củng cố kiến thức lớp 6 - 9, chuẩn bị thi chuyển cấp và cải thiện điểm số cùng gia sư EduX.",
    stats: [
      { value: "18", label: 'môn học' },
      { value: "980+", label: 'gia sư' },
      { value: "Từ 110k", label: '/giờ' },
      { value: 'Linh hoạt', label: 'Online & trực tiếp' },
    ],
  },
  searchPlaceholder: "Tìm môn học cấp THCS...",
  gridTitle: "Danh Sách Môn Học THCS",
  gridSubtitle: "Chọn môn học phù hợp để củng cố kiến thức và chuẩn bị tốt cho kỳ thi chuyển cấp.",
  pathTitle: "Lộ Trình Học THCS Gợi Ý",
  tutorsTitle: "Gia Sư Nổi Bật Cho THCS",
  ctaTitle: "Chưa Biết Nên Tập Trung Môn Nào?",
  ctaText: "Trả lời vài câu hỏi ngắn, EduX sẽ gợi ý môn học và gia sư phù hợp với mục tiêu học tập, điểm số hiện tại và kỳ thi sắp tới.",
};

export const THPT_LEVEL = {
  key: 'thpt',
  subjects: THPT_SUBJECTS,
  filterChips: THPT_CHIPS,
  learningPath: THPT_PATH,
  featuredTutors: THPT_TUTORS,
  hero: {
    title: "Môn Học Cấp THPT",
    subtitle: "Khám phá các môn học lớp 10 - 12, luyện thi THPT Quốc gia và cải thiện điểm số cùng gia sư EduX.",
    stats: [
      { value: "22", label: 'môn học' },
      { value: "1.250+", label: 'gia sư' },
      { value: "Từ 120k", label: '/giờ' },
      { value: 'Linh hoạt', label: 'Online & trực tiếp' },
    ],
  },
  searchPlaceholder: "Tìm môn học trong cấp THPT...",
  gridTitle: "Danh Sách Môn Học THPT",
  gridSubtitle: "Chọn môn học phù hợp với mục tiêu học tập của bạn.",
  pathTitle: "Lộ Trình Học THPT Gợi Ý",
  tutorsTitle: "Gia Sư Nổi Bật Cho THPT",
  ctaTitle: "Chưa Biết Nên Chọn Môn Nào?",
  ctaText: "Trả lời vài câu hỏi ngắn, EduX sẽ gợi ý môn học và gia sư phù hợp với mục tiêu của bạn.",
};
